# Generated by Django 4.1 on 2022-08-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='mood',
        ),
    ]
